\documentclass{article}
\usepackage[margin=1in]{geometry}

\begin{document}

\title{Defence presentation outline}
\author{Christophe Rouleau-Desrochers}
\date{\today}
\maketitle

% The student presents a brief summary of the thesis (not to exceed 20 minutes). Each examiner then asks questions in the general area of the thesis for 15-20 minutes, with the option of a brief second round for follow-up questions. The Chairperson may ask a question or two out of interest or for purposes of clarification but is not expected to do so. The Chair then invites questions from the audience. The exam should not exceed 2 hours. Following the examination, the candidate and audience members are asked to leave the room or virtual session so that the committee may evaluate the student’s performance.

\begin{enumerate}

\item Content (1 min)
  \begin{enumerate}
  \item Intro, chapter 1, chapter 2, conclusion; will last 15-20 minutes.
  \end{enumerate}
  
\item Introduction
  \begin{enumerate}
  \item ACC lengthens growing seasons
    \begin{enumerate}
    \item Happens through earlier SOS + delayed EOS
    \item (Figure): conceptual figure simplified showing SOS and EOS shifts
    \end{enumerate}
    
  \item GS are longer, but also warmer
    \begin{enumerate}
    \item Total annual GDD increases
    \item (Figure): conceptual figure with GDD accumulation curve 
    \end{enumerate}
  
  \item SOS + EOS shifts = more GDD, but shifts are assymetric
    \begin{enumerate}
    \item Impacts how much GDD is accumulated in the GS
    \item SOS shift more, but are cooler
    \item EOS shift less, but are warmer
    \item (Figure): conceptual figure with showing how much GDD in each season
    \end{enumerate}
    
  \item SOS + EOS shifts = longer and warmer seasons; should increase growth
    \begin{enumerate}
    \item Recent studies failed to find this relationship
    \item Important because temperate forest= 40\% of global net carbon sink
    \item (Figure): TBD
    \end{enumerate}
    
  \item Question: do trees grow more with longer and warmer seasons?
    \begin{enumerate}
    \item Objectives: address GS/growth disconnection using two systems
    \item Chapter 1: juvenile trees, 4 species, 4 prov, leaf phenology and tree rings
    \item Chapter 2: mature trees, 11 species, leaf phenology and tree rings
    \end{enumerate}
    
  \item Recent research showed that this may not be the case
    \begin{enumerate}
    \item 1
    \end{enumerate}
  
  \item Drought and competition as potential growth inhibitors and internal constraints
    \begin{enumerate}
    \item 1
    \end{enumerate}
  
  \item Questions: do longer and warmer seasons increase growth in juvenile and mature trees?
    \begin{enumerate}
    \item 1
    \end{enumerate}
  
  \item Objectives: answer this question using north american juvenile trees of 4 species from 4 provenances (chapter 1) and mature trees of 11 species (chapter 2)
    \begin{enumerate}
    \item 1
    \end{enumerate}
  
  \end{enumerate}

\item Chapter 1
  \begin{enumerate}
  \item Introduction: gs conceptual figure
  \item Introduction: constraints on growth
  \item Methods: trees grown from seeds and sourced from 4 provenances; 3.5 degree lat gradient; phenology for 3 years, growth with tree rings
  \item Methods: bayesian hierarchical models? 4 different predictors
  \item R/D: More species grew more with warmer seasons than calendar season; because warmer is a better predictor of growth
  \item R/D: Later EOS increased growth more than SOS; because higher temperature than SOS; suggests looking more at EOS
  \item R/D: No provenance effect; at least for this small gradient, no evidence of local adaptation on growth
  \item Conclusion: juvenile trees should grow more, means it would be good for range expansion and forest regenaration
  \end{enumerate}

\item Chapter 2
  \begin{enumerate}
  \item Introduction: different growth strategies could influence tree growth responses to GS length
  \item Introduction: fast vs slower growing species
  \item Introduction: wood porousness and timing of leaf phenology and growth = differences in temperature experienced; also correlates with different life-history strategies
  \item Introduction: carbon investment in storage may blur annual growth responses
  \item Methods: citizen science leaf phenology; growth with tree rings at the arboretum
  \item Methods: stats? Same predictors, but used leaf coloring as EOS.
  \item R/D: very little effect of season length 
  \end{enumerate}

\item Conclusion
  \begin{enumerate}
  \item 1
  \item 2
  \end{enumerate}

\end{enumerate}

\end{document}
