\documentclass{article}
\usepackage[margin=0.7in]{geometry}

\begin{document}

\title{Defence presentation outline}
\author{Christophe Rouleau-Desrochers}
\date{\today}
\maketitle

% The student presents a brief summary of the thesis (not to exceed 20 minutes). Each examiner then asks questions in the general area of the thesis for 15-20 minutes, with the option of a brief second round for follow-up questions. The Chairperson may ask a question or two out of interest or for purposes of clarification but is not expected to do so. The Chair then invites questions from the audience. The exam should not exceed 2 hours. Following the examination, the candidate and audience members are asked to leave the room or virtual session so that the committee may evaluate the student’s performance.

\begin{enumerate}

\item Content (1 min)
  \begin{enumerate}
  \item I'll walk you through back ground my thesis addresses (Intro), both of these chapters (1 and 2) will address this question, but I'll start with the background first and finish with a conclusion; will last 15-20 minutes.
  \item We don't have a lot of info on growing season length and growth relationship; I'll add data to this question in two systems that I find interesting.
  \end{enumerate}
  
\item Introduction
  \begin{enumerate}
  \item ACC lengthens growing seasons
    \begin{enumerate}
    \item Happens through earlier bigger shifts in SOS, and smaller delayed EOS
    \item (Figure): conceptual figure simplified showing SOS and EOS shifts
    \end{enumerate}
    
  \item GS are longer, but also warmer which should increase growth
    \begin{enumerate}
    \item Total annual GDD increases
    \item (Figure): conceptual figure with GDD accumulation curve 
    \end{enumerate}
  
  \item SOS + EOS shifts = more GDD, but shifts are assymetric (both in how many days, but also for warmth)
    \begin{enumerate}
    \item Impacts how much GDD is accumulated in the GS
    \item SOS shift more, but are cooler
    \item EOS shift less, but are warmer
    \item (Figure): conceptual figure with showing how much GDD in each season
    \end{enumerate}
    
  \item Recent studies failed to find this relationship (growth X GSL and thermal season)
    \begin{enumerate}
    \item Important because temperate forest= 40\% of global net carbon sink
    \item (Figure): TBD
    \end{enumerate}
    
  \item Question: do trees grow more with longer and warmer seasons?
    \begin{enumerate}
    \item Objectives: address GS/growth relationship using two systems
    \item Chapter 1: juvenile trees, 4 species, 4 prov, leaf phenology and tree rings
    \item Chapter 2: mature trees, 11 species, leaf phenology and tree rings
    \item (Figure): simplified version of thesis overview figure
    \end{enumerate}
    
  \end{enumerate}

\item Chapter 1
  \begin{enumerate}
  \item Introduction: 
    \begin{enumerate}
    \item Drought and competition could constrain growth
    \item Internal constraints (local adaptation?)
    \item Answer if juvenile trees grow more in a drought and competition limited environment
    \item (Figure):
    \end{enumerate}
    
  \item Methods: common garden set up
    \begin{enumerate}
    \item Trees grown from seeds, 4 species, 4 provenances 
    \item Phenology for 3 years
    \item Calendar and thermal season from leafout to budset
    \item Growth via tree rings
    \item Bayes hierarchical model
    \item (Figure): map and common garden photo
    \end{enumerate}
    
  \item R/D: thermal $>$ calendar (question reminder)
    \begin{enumerate}
    \item Calendar season increased growth only for 2 species. Weaker effect is what people found in the litterature
    \item 3 species grew more with warmer thermal season
    \item Species grew more with warmer seasons than longer calendar season
    \item Because thermal is a better predictor of growth
    \item Thermal season weights growth days while calendar assumes a stable growth rate throughout the season
    \item (Figure): 2 pannel mu plot for GDD and GSL
    \end{enumerate}
  
  \item R/D: EOS $>$ SOS; 
    \begin{enumerate}
    \item EOS temperature higher temperature than SOS 
    \item EOS delayed less, but contribution is higher because days are warmer
    \item Suggests looking more at EOS than SOS
    \item (Figure): 2 pannel mu plot for EOS and SOS AND conceptual figure showing GDD differences at EOS and SOS
    \end{enumerate}
  
  \item R/D: No provenance effect; 
    \begin{enumerate}
    \item In this small climatic gradient and range, no evidence of local adaptation on growth
    \item Transition from juvenile to mature trees
    \item (Figure): provenance mu plot
    \end{enumerate}
    
  % \item Conclusion: juvenile trees should grow more, means it would be good for range expansion and forest regenaration
  \end{enumerate}

\item Chapter 2
  \begin{enumerate}
  \item Introduction: (we have more data (but same data of rings and pheno), so well be able to ask this additional question on previous year conditions with a perpective on life history strategies could inform tree growth responses
    \begin{enumerate}
    \item Fast vs slower growing species
    \item Diffuse vs ring porous species
    \item Carbon allocation to storage = blur annual growth response to thermal and calendar seasons
    \end{enumerate}

  \item Methods: citizen science leaf phenology at the Arboretum
    \begin{enumerate}
    \item Growth via tree rings 
    \item Leaf phenology 
    \item 11 angiosperm deciduous species spanning different growth strategies and wood porousness
    \item Bayes hierarchical model
    \item (Figure): Arboretum map AND core scans
    \end{enumerate}
    
  \item R/D: weak response across species across current year predictors
    \begin{enumerate}
    \item Ball decreased growth: southernmost range reduction in future ACC
    \item Tiam: grew less with earlier SOS despite being fast growing 
    \item No consistent trend across life history strategies or wood porousness
    \item (Figure): mu plots 4 facet
    \end{enumerate}
  
  \item R/D: 2 species responded to previous year thermal season
    \begin{enumerate}
    \item Ball increase growth with previous yr condition
    \item Bnig grew more only when considering previous yr condition
    \item Maybe suggests importance of carbon allocation to storage for mature trees; blur responses
    \item (Figure): previous year conditions mu plot
    \end{enumerate}
  
  \end{enumerate}

\item Conclusion and future work
  \begin{enumerate}
  \item Chapter 1 and 2
    \begin{enumerate}
    \item Chapter 1: warmer seasons for juvenile trees = good for forest regeneration and range expansion
    \item Chapter 2: no effect of longer and warmer seasons: probably bad for forest carbon
    \item (Figure): simplified version of thesis overview figure
    \end{enumerate}

    
  \end{enumerate}

\end{enumerate}

\end{document}
